services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres